# -*- coding: utf-8 -*-
<MakeResultTimesTablePageWidget@BoxLayout>:
    BoxLayout:
        orientation: 'vertical'

        canvas.before:
            Color:
                rgba: 0.7,0.6,0.4,1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            size_hint_y: 0.1
            text: 'Result'
            text_size: self.size
            halign: 'left'
            valign: 'top'
            font_size: 30
            color: [0, 0, 0, 1]

        BoxLayout:
            id:Result
            orientation: 'vertical'
            size_hint_y: 0.8
            canvas.before:
                Color:
                    rgba: 245/255, 245/255, 245/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

        Button:
            size_hint_y: 0.1
            background_normal:''
            background_color:(0.2, 0.7, 0.5, 1)
            text: 'UNDO'
            color: [0, 0, 0, 1]
            font_size: 30
            on_press:app.root.gotoMakeCode()

            