# -*- coding: utf-8 -*-
<MakeCodeWidget@BoxLayout>:
    BoxLayout:
        size_hint_x: 0.3

        canvas.before:
            Color:
                rgba: 0.7,0.6,0.4,1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            id: LabelExplanatoryText
            text: ''
            text_size: self.size
            halign: 'left'
            valign: 'top'
            font_size: 30
            color: [0, 0, 0, 1]
        
    BoxLayout:
        orientation: "vertical"
        size_hint_x: 0.7

        BoxLayout:
            canvas.before:
                Color:
                    rgba: (0.6, 0.8, 0.9, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint_y: 0.1

            BoxLayout:
                padding: 3
                spacing: 3
                Label:
                    size_hint_x: 0.6
                    text: 'MENU'
                    color: [0, 0, 0, 1]
                    font_size: 30

                ButtonAction:
                    size_hint_x: 0.2
                    background_normal:''
                    background_color:(0.2, 0.7, 0.5, 1)
                    text: 'SelectMenu'
                    color: [0, 0, 0, 1]
                    font_size: 30
                    on_press:app.root.gotoMenu()

                ButtonAction:
                    size_hint_x: 0.2
                    background_normal:''
                    background_color:(0.2, 0.7, 0.5, 1)
                    text: 'Exec'
                    color: [0, 0, 0, 1]
                    font_size: 30
                    on_press:app.root.gotoResultMakeCode()
                        
                ButtonAction:
                    size_hint_x: 0.2
                    background_normal:''
                    background_color:(0.9,0.5,0,1)
                    text: 'Save'
                    color: [0, 0, 0, 1]
                    font_size: 30
                    on_press:self.confirmSaveFilePopup()

        TextInput:
            id: TextInputEditCode
            text: 'Input Code'
            color: [0, 0, 0, 1]
            font_size: 30
            background_color: [1, 1, 1, 1]
            size_hint_y: 0.9
